services:
  postgres:
    image: postgres:17.5
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: steamreviews
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      restart: always
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: mypgadminpass
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        - postgres
volumes:
  postgres_data:
  pgadmin_data: